package org.mskcc.kickoff.printer;

public enum ErrorCode {
    AMBIGUOUS_PAIREDNESS,
    FASTQ_DIR_NOT_FOUND,
    NO_SAMPLE_MAPPINGS,
    PAIREDNESS_RETRIEVAL_ERROR,
    REQUEST_INFO_MISSING,
    SEQUENCING_FOLDER_NOT_FOUND,
    UNMATCHED_NORMAL,
    UNMATCHED_TUMOR,
    EXTERNAL_SAMPLE_NOT_FOUND;
}
