test.integration.roslin.manifestOutputFilePath=integration-test/manifests/roslin
test.integration.roslin.manifestArchivePath=integration-test/archive/roslin
test.integration.roslin.manifestCompareToFilePath=/home/feng/dev/manifests
test.integration.bic.manifestOutputFilePath=integration-test/manifests/bic
test.integration.bic.manifestArchivePath=integration-test/archive/bic
test.integration.bic.manifestCompareToFilePath=/ifs/projects/BIC/drafts
test.integration.bic.projectIds=06260_N,05862_Y
test.integration.roslin.projectIds=05862_Y,06058_I,07951_R,set_09413_E,set_07871_F
test.integration.fastq_path=/ifs/archive/GCL